server:
  port: 8080
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8


spring:
  thymeleaf:
        mode: HTML
        prefix: classpath:/templates/
        suffix: .html
        cache: false

  datasource:
    url: jdbc:mysql://localhost:3306/blockchainshow?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    username : root
    password : root
    driverClassName : com.mysql.cj.jdbc.Driver
  resources:
    static-locations: classpath:/static/,file:static/